import './globals.css'

export default function DashboardLayout({
	                                   children,
                                   }: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
		<head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/public/favicon.ico" />
		</head>
		<body>{children}</body>
		</html>
	)
}
